### ISSUE TITLE
Besoin de votre aide pour créer une automation 

### ISSUE THREAD

**Issue by Telyoussoufi** [doudz/homeassistant-zigate#115]
Bonjour,
débutant dans HASS , je viens d’installer une box home assistant (sur raspeberry) et aquerir une zigate que je compte utiliser essentiellement pour contrôler des interrupteurs Aqara simple et double (sans fil) + des interrupteurs ( sans fil ) simple et double aussi pour créer des va et vient.

Alors mon problème concerne la création des automatismes des va et vient.
exemple : 
mon interrupteur sans fil : 
sensor.zigate_00158d000322d185_multiclick
mon interrupteur filaire à contrôler pour créer le va et vient : 
switch.zigate_00158d0004246be3_2

j'essaye de créer une automatisation classique 
quand je fais un simple appuie sur le sans fil + interrupteur éteint ------>interrupteur allumé
quand je fais un simple appuie sur le sans fil + interrupteur allumé------>interrupteur éteint 

- id: '1588119067218'
  alias: SAMVaetvient
  description: ''
  trigger:
  - event_data:
      entity_id: sensor.zigate_00158d000322d185_multiclick
    event_type: zigate.attribute_updated
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.zigate_00158d00045fa61f_2
    service: switch.toggle

Mon code est bien compilé mais ne marche pas quand j'actionne l'interrupteur sans fil.

D'avance merci pour votre aide

**Comment by Amaurgit** [comment]
Tu peux regarder dans home assistant les events qui sont générés dans "Outils de développement/événements".

Commence par regarder l'event qui est envoyé quand tu appuies sur ton interrupteur sans fil.
Ca m'étonne que tu ne puisse pas récupérer un state sur le sans fil, ce qui serait plus simple à gérer :)

Si state sans fil = on & state filaire = off alors state_filaire = on
Si state sans fil = on & state filaire = on alors state_filaire = off

A voir si tu as ces states, sinon on verra pour l'event :) 
Poste nous tes retours !

**Comment by doudz** [comment]
Voici ce que j'utilise pour le va et vient avec des switch XIAOMI (avec et sans fil)
```
- id: '1585843784562'
  alias: VAV Entrée
  description: ''
  trigger:
  - entity_id: sensor.zigate_00158d000424ad57_multiclick2
    platform: state
    to: '1'
  condition: []
  action:
  - data: {}
    entity_id: switch.zigate_00158d0002ab638b_3
    service: switch.toggle
```
