### ISSUE TITLE
[HELP WANTED] Wait template sur un switch Xiaomi

### ISSUE THREAD

**Issue by Bredin76** [doudz/homeassistant-zigate#135]
Bonjour,

Je souhaite commander une lumière avec un bouton xiaomi en prévoyant une temporisation
Cinématique attendue :
- Je clique sur le bouton => la lumière s'allume => Si dans les 5 minutes qui suivent le bouton n'est pas cliqué à nouveau ( pour éteindre) alors l'automation éteint la lumière. 
( c'est un automatisme qui pense à éteindre la lumière des WC à la place de mon gamin... " C'est pas Versailles ici !") 

Je vois ça sous la forme d'une automation 
```
- id: '1598608713975'
  alias: Gestion lumière WC
  description: ''
  trigger:
  - event_data:
      entity_id: zigate.00158d00023335ce
      name: onoff
      value: true
    event_type: zigate.attribute_updated
    platform: event
  - event_data:
      entity_id: zigate.00158d00023e8541
      name: onoff
      value: true
    event_type: zigate.attribute_updated
    platform: event
  condition: []
  action:
    entity_id: light.zigate_0017880102c54080_11
    service: light.turn_on
``wait_template: "{{ is_state( trigger.entity_id, 'on') }}"
  timeout: '00:05:00'`` 
    entity_id: light.zigate_0017880102c54080_11
    service: light.turn_off
  mode: single
```
Vous l'aurez compris, je cherche à reproduire le trigger d'entrée dans l'automation dans le ``wait`` 
``wait_template: "{{ is_state( trigger.entity_id, 'on') }}"
  timeout: '00:05:00'`` 
et là, ca dépasse mes compétences. 
J'ai beau éplucher la doc des `states` et de ``zigate``, je ne trouve pas de solutions. 

Quand je récupere les ``states`` disponibles dans le domaine ``zigate`` je ne vois rien avec le nom ``onoff`` que je cherche. 

Il me manque sans doute une clef de logique... 

du coup j'ai bricolé en découvrant que le ``state`` disponible sur mon bouton correspond grosso-modo au moment ou il a été cliqué pour la dernière fois. challenge donc ce ``state`` avec ``now()`` 
et j'ai du ajouter un délai avant le ``wait`` pck il capte 2 clic semble t-il ( j'appuis et je relâche ) donc ma lumière restait allumée seulement le temps ou j'avais le doigt sur le bouton) 

``
- id: '1598608713975'
  alias: Gestion lumière WC
  description: ''
  trigger:
  - event_data:
      entity_id: zigate.00158d00023335ce
      name: onoff
      value: true
    event_type: zigate.attribute_updated
    platform: event
  - event_data:
      entity_id: zigate.00158d00023e8541
      name: onoff
      value: true
    event_type: zigate.attribute_updated
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: light.zigate_0017880102c54080_11
    service: light.turn_on
  - delay: 00:00:04
  - timeout: 00:05:00
    wait_template: '{{ as_timestamp(states(''zigate.00158d00023e8541''))|int - as_timestamp(now())|int
      == 0 }}'
  - data: {}
    entity_id: light.zigate_0017880102c54080_11
    service: light.turn_off
  mode: single
``

Pouvez vous m'aider ? 

NOTA : S'il y a de la doc quelque part pour savoir comment récupérer des informations en provenance de la zigate je suis prenneur...

**Comment by doudz** [comment]
Et pourquoi pas simple
```
- id: '1598608713975'
  alias: Gestion lumière WC
  description: ''
  trigger:
  - platform: state:
      entity_id: light.zigate_0017880102c54080_11
      to: on
      for:
        minutes: 5
  action:
    entity_id: light.zigate_0017880102c54080_11
    service: light.turn_off
```
