### ISSUE TITLE
Probleme switch IKEA E1743

### ISSUE THREAD

**Issue by vini59fr** [doudz/homeassistant-zigate#143]
Bonjour Doudz

J'ai un problème avec un switch IKEA E1743 (le modele tout simple, juste un on/off)
Il est bien reconnu dans Zigate Admin mais il est inopérant. J'ai aussi une prise electrique IKEA qui elle fonctionne bien

J'ai remarqué une chose bizarre : 
- la prise zigate.xxxxda28b a 2 entités, dont une qui commence par switch et qui a un etat on ou off
- l'interrupteur zigate.xxx16f12 n'a pas cette 2eme entité et je pense que c'est là le probleme

J'ai déjà supprimé et réassocier, ca reste toujours pareil

![2020-10-01 21 26 17](https://user-images.githubusercontent.com/65531566/94856059-baddbc80-042f-11eb-80db-cdbc684db5b8.jpg)

**Comment by MichaelBitard** [comment]
J'ai exactement le même souci. 

J'ai vu sur la documentation zigate (https://zigate.fr/produits-ikea-tradfri-compatibles-zigate/compatible/ikeatlcommande/) que cette télécomande était particulière, que pour l'appairer à un autre module zigbee il fallait mettre l'autre module dans le bon groupe.

Du coup j'ai 2 questions :
- est-ce que ça veut dire que cet interrupteur ne peut pas fonctionner tout seul ?
- comment associer à un groupe depuis l'interface d'admin ?

@vini59fr si tu penses que je hijack ton issue j'en referais une à côté.

**Comment by vini59fr** [comment]
@MichaelBitard pas de souci et bien content que tu complete, je me sentais bien seul sans reponse
je vais regarder ton lien et voir ce qui peut etre fait

Sur d'autres support Zigbee, ca semble fonctionner normalement pourtant :/

**Comment by vini59fr** [comment]
> J'ai exactement le même souci.
> 
> J'ai vu sur la documentation zigate (https://zigate.fr/produits-ikea-tradfri-compatibles-zigate/compatible/ikeatlcommande/) que cette télécomande était particulière, que pour l'appairer à un autre module zigbee il fallait mettre l'autre module dans le bon groupe.
> 
> Du coup j'ai 2 questions :
> 
> * est-ce que ça veut dire que cet interrupteur ne peut pas fonctionner tout seul ?
> * comment associer à un groupe depuis l'interface d'admin ?
> 
> @vini59fr si tu penses que je hijack ton issue j'en referais une à côté.

Punaise, ca fonctionne !

Par contre, c'est pas top pour l'ajout de groupe, j'ai dû passer par Outils de developpement et appeler le service zigate.add_group. Il faut tout remplir manuellement

@doudz y'a pas moyen d'avoir un truc plus simple pour l'ajout de groupe dans ZigateAdmin ? Merci :)

**Comment by MichaelBitard** [comment]
@vini59fr du coup t'as associé une lampe au groupe '0x0000' c'est bien ça ? Le truc c'est que j'aimerais pas faire ça, je souhaite utiliser cette télécommande pour piloter des trucs non zigbee, donc en passant par la zigate et home assistant.

**Comment by MichaelBitard** [comment]
Même si je rajoute un élément dans le groupe, je n'arrive pas à récupérer le fait que l'élément a été activé par la télécommande (dans home assistant en tout cas).

**Comment by vini59fr** [comment]
> @vini59fr du coup t'as associé une lampe au groupe '0x0000' c'est bien ça ? Le truc c'est que j'aimerais pas faire ça, je souhaite utiliser cette télécommande pour piloter des trucs non zigbee, donc en passant par la zigate et home assistant.

J'ai simplement suivi le lien que tu as mis. 
J'ai donc associé une prise Ikea zigbee au groupe 0000.
Je n'ai rien d'autre de pilotable actuellement (juste des capteurs de T°) 

Je comprends ce que tu veux faire, mais d'apres le site Zigate, ça n'a pas l'air possible (ça doit rester du zigbee je pense, vu qu'il faut associer le périph à contrôler dans le groupe 0000)

**Comment by MichaelBitard** [comment]
Mon idée c'était juste d'arriver à capter les événements de la télécommande zigbee pour après, programmatiquement, déclencher d'autres choses via home assistant.
C'est là où l'aide de @doudz peut être utile, pour nous dire si c'est faisable, ou si ce n'est pas comme ça que ça fonctionne, tout simplement.

**Comment by doudz** [comment]
Pour récupérer les évènements de la télécommande il faut mettre la Zigate dans un groupe (0000 par exemple) et la télécommande dans ce même groupe. Pas besoin de mettre l'ampoule dans le groupe, si on le fait alors l'ampoule va réagir directement à la télécommande et ce n'est pas ce qui est voulu

**Comment by guirem** [comment]
Bonsoir,

Normalement une fois que tu as mis dans le groupe 0 et après avoir cliquer sur le boutons à plusieurs reprises tu devrais avoir 2 sensors de ce type (l'id sera différent):
- sensor.zigate_000d6ffffeda23d0_remote_onoff_button
- sensor.zigate_000d6ffffeda23d0_remote_level_button

Ensuite à toi de créer des _automations_ pour détecter les changement d'états sur ces capteurs.

Voici un exemple qui fonctionne chez moi et qui reprend il me semble l'ensemble des actions possibles à savoir 
- appui court sur '1'
- appui court sur '0'
- appui long sur '1'
- appui long sur '0'

```
- id: '1580247406357'
  alias: Eteindre Petite Ambiance Salon
  description: ''
  trigger:
  - entity_id: sensor.zigate_000d6ffffeda23d0_remote_onoff_button
    platform: state
    to: middle_0
  condition: []
  action:
  - entity_id: group.salon_ambiance_lumiere_1
    service: homeassistant.turn_off
    
- id: '1580389790357'
  alias: Allumer Petite Ambiance Salon
  description: ''
  trigger:
  - entity_id: sensor.zigate_000d6ffffeda23d0_remote_onoff_button
    platform: state
    to: middle_1
  condition: []
  action:
  - entity_id: group.salon_ambiance_lumiere_1
    service: homeassistant.turn_on
    
- id: '1580389899144'
  alias: Allumer Ambiance Salon
  description: ''
  trigger:
  - entity_id: sensor.zigate_000d6ffffeda23d0_remote_level_button
    platform: state
    to: up_hold
  condition: []
  action:
  - entity_id: group.salon_ambiance_lumiere
    service: homeassistant.turn_on
    
- id: '1581791012144'
  alias: Eteindre Ambiance Salon
  description: ''
  trigger:
  - entity_id: sensor.zigate_000d6ffffeda23d0_remote_level_button
    platform: state
    to: down_hold
  condition: []
  action:
  - entity_id: group.salon_ambiance_lumiere
    service: homeassistant.turn_off
```
