### ISSUE TITLE
Aqara button click not detected

### ISSUE THREAD

**Issue by bokub** [doudz/homeassistant-zigate#79]
Hi ! First of all, thanks for this amazing component !

So I have a simple aqara button. If I click one or multiple times, the `zigate.xxx` entity is updated as expected, but most of the times, the associated `binary_sensor.xxx` (single click) and `sensor.xxx` (multi-click) are not updated...

![image](https://user-images.githubusercontent.com/17952318/66767883-a9fc0a00-eeb1-11e9-929c-220d1a3fb6bd.png)

So I can detect when the button is clicked, but I cannot really differentiate a single click from a double or triple click...

I tried subscribing to `zigate.attribute_updated`, but what happens when I click 2 times is that **it triggers 2 events** !

I know it looks like #42 but is there a way to fix that ? Maybe a way to increase the timeout between 2 events ?
Thanks a lot 👍

**Comment by doudz** [comment]
For single click I use something like this:

```
trigger:
  - event_data:
      attribute: 0
      cluster: 6
      endpoint: 1
      ieee: 00158d00016c487e
      value: true
    event_type: zigate.attribute_updated
    platform: event
```

**Comment by bokub** [comment]
Yeah, I managed to solve the problem using events, as suggested

For single click:

```yaml
entity_id: zigate.my_button
name: onoff
value: true
```

For multiclick:

```yaml
entity_id: zigate.my_button
name: multiclick
value: 2
```

And I have noticed something really important too:

**Multi clicks should not be too fast, or they will be detected as multiple single clicks**
